<?php

namespace Database\Seeders;

use App\Enums\ContentStatus;
use App\Enums\ExerciseDifficulty;
use App\Enums\ProvenanceSource;
use App\Models\Concept;
use App\Models\InterviewQuestion;
use Illuminate\Database\Seeder;

/**
 * ~80 interview questions (docs/15 Phase 9, FR-31): grouped by topic
 * (oop, core, patterns, architecture, testing, database), each with a model
 * answer, follow-ups and an optional concept link. Deterministic and
 * idempotent (updateOrCreate on question text).
 */
class InterviewQuestionSeeder extends Seeder
{
    /**
     * [topic, difficulty, concept slug|null, question, model answer, follow-ups]
     *
     * @var list<array{string, string, string|null, string, string, list<string>}>
     */
    private const QUESTIONS = [
        // --- OOP (18) ---
        ['oop', 'easy', 'class', 'What is the difference between a class and an object?', 'A class is the blueprint: it declares state and behaviour. An object is a runtime instance of that blueprint, with its own identity and property values. You define a class once and can create many objects from it.', ['If two objects hold identical values, are they the same object?', 'Where does PHP keep track of an object\'s class at runtime?']],
        ['oop', 'easy', 'constructor_promotion', 'What does constructor property promotion do and what problem does it solve?', 'PHP 8 lets you declare a constructor parameter and its property in one step: public function __construct(private string $name) {}. It removes repetitive property-plus-assignment boilerplate while keeping the same visibility control.', ['Can promoted properties be non-public or nullable?', 'What does the compiler generate under the hood?']],
        ['oop', 'easy', 'visibility', 'When would you choose protected over private?', 'Use protected when subclasses genuinely need to reuse or override the member as part of the template. Prefer private by default: protected widens the API to every subclass and couples you to your own inheritance tree.', ['What danger does wide protected access create?', 'How does visibility relate to encapsulation?']],
        ['oop', 'medium', 'composition', 'Favour composition over inheritance — what does that mean in practice?', 'Build classes from other objects (has-a) rather than deriving them from a base class (is-a). Composition keeps dependencies explicit, lets behaviour vary at runtime through injection, and avoids fragile base-class coupling where a parent change breaks every child.', ['Give a PHP example where inheritance would hurt.', 'How does composition help testing?']],
        ['oop', 'medium', 'interface', 'Interface vs abstract class: how do you decide?', 'An interface defines a contract any class can implement, often several times — use it for capabilities (Renderable, Payable). An abstract class shares state and partial implementation among closely related subclasses — use it when there is a real is-a hierarchy with common code. PHP allows only single inheritance of classes but unlimited interfaces.', ['When would you use both together?', 'What does an interface guarantee about implementation?']],
        ['oop', 'easy', 'polymorphism', 'What is polymorphism and where does PHP apply it?', 'One interface, many implementations, chosen at runtime: a loop over Renderable objects calls render() and each class does its own thing. PHP dispatches method calls dynamically on the object\'s actual class, so adding a new class needs no change at the call site.', ['How does it differ from function overloading?', 'What breaks polymorphism (e.g. instanceof chains)?']],
        ['oop', 'medium', 'inheritance', 'What are the classic smells of overusing inheritance?', 'Deep hierarchies, downcasts, sibling classes duplicating code, and base-class changes breaking children. If you find yourself overriding a method just to negate or stub parent behaviour, you likely want composition or an interface instead.', ['What is the fragile base class problem?', 'How do you refactor an overgrown hierarchy?']],
        ['oop', 'medium', 'trait', 'What do traits solve, and what are their drawbacks?', 'Traits compose methods horizontally when a class can only extend one parent (e.g. Loggable + Serializable). Drawbacks: they flatten the hierarchy, can collide on method names, and hide where behaviour comes from — prefer explicit composition when you can.', ['What happens when two traits define the same method?', 'How do you resolve a trait conflict?']],
        ['oop', 'medium', 'magic_methods', 'Which magic methods would you actually implement, and why?', '__construct always; __toString to make objects printable/concatenable; __get/__set only for genuinely dynamic access patterns; __invoke when a callable object is clearer than a closure. Avoid __call unless you are building a DSL — it hides missing methods from static analysis.', ['Why is __call dangerous for refactoring?', 'When is __toString the right choice?']],
        ['oop', 'easy', 'object_identity', 'What is the difference between == and === for objects?', '== compares class and property values (loose equality of attributes); === requires the same instance — the same object in memory. Two separately created objects with identical fields are == but never ===.', ['Which should array keys or deduplication use?', 'Where does === matter for singletons?']],
        ['oop', 'medium', 'encapsulation', 'Encapsulation is more than getters and setters — explain.', 'Encapsulation groups state with the invariants that protect it and hides representation details. Instead of exposing a setDueDate() setter, expose renew() that enforces due-date rules — callers cannot put the object into an illegal state because the only paths to state are guarded methods.', ['How does hiding storage help evolution?', 'What is an anemic model (the opposite)?']],
        ['oop', 'easy', 'design_principles', 'Explain the Single Responsibility Principle in one sentence.', 'A class should have one reason to change — one job, one axis of change: if parsing, pricing and PDF rendering all live together, every one of those concerns forces edits to the same file.', ['How do you spot a violation when reviewing code?', 'What is the cost of ignoring it?']],
        ['oop', 'medium', 'design_principles', 'Open/closed: how would you apply it in PHP?', 'Extend behaviour by adding new classes rather than editing existing ones. Implement a Sender interface, then add SmsSender and PushSender — the hub that iterates Senders never changes. Open for extension, closed for modification.', ['What PHP features help (interfaces, attributes, first-class callables)?', 'When does OCP become speculative abstraction?']],
        ['oop', 'hard', 'design_principles', 'What is the Liskov Substitution Principle and how can PHP code violate it?', 'Subtypes must be substitutable: any place a base type works, a subtype must work too without callers noticing. Violations include a Square extending Rectangle and invalidating setWidth(), or a subclass throwing where the parent contract allowed the call — breaks in every caller.', ['How do return-type covariance rules relate?', 'What is a design-by-contract approach to preventing it?']],
        ['oop', 'medium', 'di', 'You need a logger inside a service. Why inject it instead of new Logger() inside the class?', 'Injection keeps the service decoupled from the concrete logger: tests substitute a fake, production swaps implementations, and the dependency is visible in the constructor signature. Constructing internally hard-codes the choice and forces global state or hard-to-reach configuration.', ['What is the manual (poor man\'s) DI approach?', 'When does a DI container actually earn its keep?']],
        ['oop', 'medium', 'static', 'When are static methods acceptable, and when do they hurt?', 'Fine for stateless utilities (parsing, math) and true factories with no instance state. Hurtful when they reach for globals or singletons: static calls cannot be faked or swapped in tests, and they hide coupling. Prefer instance methods once behaviour needs configuration.', ['Why are static calls hard to mock?', 'How do facades relate to this risk?']],
        ['oop', 'easy', 'readonly', 'What does readonly give you in PHP 8.1+?', 'Readonly properties can be initialised only once, from inside the class scope — assignment anywhere else throws. It makes value objects genuinely immutable, which simplifies reasoning and makes objects safe to share between components.', ['Can readonly be combined with constructor promotion?', 'What happens to readonly on arrays or objects?']],
        ['oop', 'hard', 'reflection', 'What is reflection, and what is it typically misused for?', 'Reflection API inspects classes, methods, parameters and attributes at runtime — great for framework magic, serializers and DI containers. Misused when it pierces private state to patch values, when it duplicates logic normal methods should do, or when it hides control flow from readers.', ['How do attributes reduce the need for reflection hacks?', 'What performance cost does reflection carry?']],

        // --- Core PHP (18) ---
        ['core', 'easy', 'operators', 'Difference between == and === in PHP?', '== compares values after type juggling (\'10\' == 10 is true); === compares value AND type strictly (\',10\' === 10 is false). Use === by default and reserve == for deliberate loose comparisons — most PHP bugs come from the coercion.', ['What about == with arrays or objects?', 'When is == intentionally useful?']],
        ['core', 'medium', 'type_coercion', 'What is type juggling and how does it cause bugs?', 'PHP converts types automatically in loose contexts: \'abc\' == 0 is true (non-numeric string to 0 in PHP 8 comparisons it is false — but \'10abc\' == 10 is still true). Unexpected truthiness of strings and zeros leads to wrong branches in validations.', ['Which comparison changed in PHP 8?', 'How do you defend against juggled input?']],
        ['core', 'easy', 'type_coercion', 'What does declare(strict_types=1) change?', 'It makes scalar type checks strict in THAT FILE: passing a float 1.5 where int is declared throws a TypeError instead of truncating to 1. It applies to calls made from that file — not globally — and never affects return types of other files.', ['Does it affect method calls inside the file too?', 'Why is it per-file, not a php.ini switch?']],
        ['core', 'easy', 'null_safe_operator', 'Explain ?-> and the ?? operator — when do you use each?', '?-> short-circuits a chain when the receiver is null: $user?->address?->city returns null instead of erroring. ?? supplies a fallback when a value is null OR missing (undefined index included). Use ?-> to walk safely, ?? to default.', ['What does ?-> return when it short-circuits?', 'How do they combine in one expression?']],
        ['core', 'easy', 'match_expression', 'How does match differ from switch?', 'match is an expression (it returns a value), uses strict === comparison, and throws UnhandledMatchError when nothing matches — no silent fall-through. switch falls through by default and coerces loosely. Prefer match for value selection.', ['What is UnhandledMatchError?', 'When is switch still appropriate?']],
        ['core', 'medium', 'arrow_functions', 'Arrow functions vs closures — when is each better?', 'fn() => single-expression functions capture variables by value automatically and are one line: array_map(fn($x) => $x * 2, $list). use ($x) closures need explicit capture, can have statements, and capture by reference option. Arrow fn for transforms, closures for multi-step logic.', ['Do arrow functions capture by value or reference?', 'Can arrow functions be nested or recursive?']],
        ['core', 'medium', 'references', 'What do references do in PHP and what problems do they cause?', '=& makes two variables share one value slot; foreach ($a as &$v) mutates $a in place. Problems: lingering references corrupt later loops (the classic foreach-by-reference bug), references in APIs make ownership unclear, and they defeat copy-on-write optimizations.', ['What is the unset($v) fix after foreach by reference?', 'How do references differ from object handles?']],
        ['core', 'medium', 'arrays', 'Are arrays copied when you pass them to a function?', 'PHP passes arrays by value using copy-on-write: modifications inside the function do not affect the caller until something writes to it. That gives value semantics cheaply. Use & $arr parameters only when the function must mutate the caller\'s array deliberately.', ['What happens with nested arrays and objects inside?', 'What does copy-on-write mean for memory?']],
        ['core', 'medium', 'generators', 'What is a generator and when would you use one?', 'A function with yield returns a lazy iterator that produces values one at a time without building the whole array in memory. Use it for large files, API pages or any stream where you process items sequentially — memory stays constant regardless of input size.', ['What does yield return to the caller?', 'How do you re-iterate a generator (it can only be walked once)?']],
        ['core', 'medium', 'iterators', 'What makes a class an Iterator in PHP?', 'Implementing Iterator (current, key, next, rewind, valid) lets foreach walk your object like an array. It lets you expose custom traversal — paging a database, filtering on the fly — without materialising everything first.', ['What does yield use under the hood?', 'When would you implement IteratorAggregate instead?']],
        ['core', 'easy', 'superglobals', 'Name the superglobals you rely on and one security rule for each.', '$_GET/$_POST for input — never trust, always validate; $_SERVER for request metadata ($_SERVER[\'REQUEST_METHOD\']); $_SESSION for per-user state; $_COOKIE only for non-sensitive identifiers since the client can tamper with them. Never concatenate superglobal values into SQL or HTML.', ['How do you read JSON input then?', 'Where does escaping belong?']],
        ['core', 'easy', 'sessions', 'How do sessions work in PHP?', 'session_start() sends a session id cookie and loads the server-side $_SESSION array for that id. State persists across requests because the server stores the data keyed by the id. Guard it: regenerate the id on login (anti-fixation) and never store secrets in it.', ['What is session fixation and how do you prevent it?', 'Where does the session data physically live?']],
        ['core', 'medium', 'error_handling', 'Errors vs exceptions in PHP 8 — how do they differ?', 'Exceptions are throwables you catch (try/catch) for recoverable application failures. Errors (TypeError, ValueError, ParseError) are engine-level throwables — also catchable, but signalling programmer mistakes, not expected business failures. Both implement Throwable since PHP 7.', ['Can you catch a TypeError?', 'What does set_error_handler still handle?']],
        ['core', 'easy', 'union_types', 'What are union types and nullable types?', 'Union types accept several alternatives: int|string, or string|false. Nullable shorthand ?int means int|null. They let signatures document reality (a value can genuinely be null or a fallback string) instead of defaulting to mixed.', ['What does mixed mean?', 'Can union types include false and null?']],
        ['core', 'easy', 'named_arguments', 'Why are named arguments useful and what is their risk?', 'array_slice($items, offset: 1, length: 5) documents intent and lets you skip optional params. Risk: renaming a parameter breaks callers at runtime — never use named args with argument unpacking of user input, and be careful refactoring public APIs.', ['How do they interact with variadics ...$args?', 'What breaks when you rename the parameter?']],
        ['core', 'easy', 'enums', 'What is an enum and when do you use one?', 'A backed enum enumerates a fixed set of values (ContentStatus::Published = \'published\'). Use it for states, types and modes instead of magic strings: invalid values become impossible, and you can attach label()/badge() methods centrally.', ['Can enums hold behaviour or only values?', 'How do you cast one from a database column?']],
        ['core', 'medium', 'property_hooks', 'What do property hooks give you in PHP 8.4?', 'Hooks intercept reads and writes: public string $slug { get => strtolower($this->value); set => trim($this->value); }. You get computed/virtual properties and validation at assignment time without exposing private storage or writing getX()/setX() boilerplate.', ['What is a virtual property (backed vs non-backed)?', 'How does this change encapsulation compared to getters?']],
        ['core', 'hard', 'fibers', 'What are fibers and what are they for?', 'Fibers are separate, suspendable call stacks: a fiber runs code and can yield control back (suspend()) mid-execution, resuming later. They enable cooperative concurrency inside one process — used by async runtimes to interleave tasks without threads or callbacks.', ['How does suspend differ from yield in a generator?', 'What can fibers NOT solve (parallelism)?']],

        // --- Patterns (15) ---
        ['patterns', 'medium', 'strategy', 'Explain the Strategy pattern with a PHP example.', 'Define an interface for a family of algorithms, implement each (DiscountStrategy: Regular, Member, Clear), and inject the chosen one at runtime. The context stops growing if/else branches — you swap behaviour by passing a different object.', ['How does this differ from a callback?', 'When is a plain callable simpler?']],
        ['patterns', 'easy', 'factory', 'What does the Factory pattern buy you?', 'It centralises object creation: one place decides which class to build from config or inputs, while callers depend only on the returned interface. Swapping implementations or adding variants touches the factory, not every call site.', ['Factory method vs simple factory?', 'When does a factory become an over-engineered switch?']],
        ['patterns', 'medium', 'static', 'What is the Singleton pattern and why is it controversial?', 'A class that allows exactly one instance, usually via a static getInstance(). Controversial because static global state hides dependencies, breaks test isolation (state leaks between tests), and couples everything to the concrete class. Use a container-injected shared instance instead when you need one instance.', ['How does a DI container give you singleton semantics without the pattern?', 'Where are singletons still acceptable?']],
        ['patterns', 'medium', 'behavioral', 'Observer vs events in an application — when do you reach for them?', 'When several independent listeners must react to one thing happening (order placed → email, ledger, analytics), decouple by notifying through an interface or event object. The subject never knows the listeners, so adding reactions does not edit the subject.', ['How does this map to Laravel events/listeners?', 'What are the debugging costs of async events?']],
        ['patterns', 'hard', 'structural', 'Decorator vs inheritance for adding behaviour?', 'A decorator wraps an object implementing the same interface and adds behaviour in its own methods, delegating the rest — behaviour can stack and vary per instance. Inheritance bakes additions into the class: static, fixed at definition, and explodes combinatorially with feature flags.', ['How does PHP\'s own class-syntax encourage decorators (e.g. streams)?', 'When would you choose a proxy instead?']],
        ['patterns', 'medium', 'di', 'Dependency injection vs a service locator — why prefer DI?', 'DI passes dependencies into a class explicitly (constructor injection); a locator is a global the class reaches into to fetch what it needs. DI makes dependencies visible in signatures and trivially faked in tests; locators hide coupling inside method bodies and behave like ambient globals.', ['What does a DI container automate?', 'Can a locator ever be reasonable (legacy code)?']],
        ['patterns', 'hard', 'structural', 'Facade vs adapter — how do they differ?', 'A facade gives a simple, unified interface over a subsystem you own (a Training facade over report + import subsystems). An adapter converts an existing foreign interface into one your code expects (payment gateway SDK behind your Payment interface). Facade simplifies; adapter translates.', ['Which one would you use for a third-party API?', 'Can a class be both?']],
        ['patterns', 'medium', 'behavioral', 'What is the Template Method pattern?', 'A base class defines the algorithm skeleton (process(): validate → transform → persist) and leaves steps as protected methods or hooks that subclasses override. Useful when the flow is stable but steps vary — but prefer composition (strategy per step) if steps need runtime swapping.', ['How does it relate to the strategy pattern?', 'What is the usual downside of template methods?']],
        ['patterns', 'medium', 'behavioral', 'When does the Iterator pattern beat an array of results?', 'When traversal should hide storage: paging the DB on demand, filtering lazily, or walking a tree. Callers foreach without knowing whether data comes from SQL, an API or memory — and memory stays flat because items materialise one at a time.', ['How does IteratorAggregate simplify this?', 'What does yield give you without a custom class?']],
        ['patterns', 'medium', 'behavioral', 'What is the Command pattern and where is it natural in PHP?', 'Wrap an action as an object (receiver + params + execute()), so you can queue, log, undo or serialize operations. Natural for job queues and CLI steps: each command is a first-class value you can retry or inspect independently of who triggered it.', ['How does this relate to Laravel jobs?', 'How would you implement undo?']],
        ['patterns', 'hard', 'behavioral', 'Chain of responsibility: what problem does it solve?', 'Let several handlers process a request in order until one accepts — each knows only the next link. Solves situations like HTTP middleware or validation pipelines where you want to add/remove steps without one god-class conditionals block.', ['What happens if no handler accepts the request?', 'How does it differ from a pipeline of transforms?']],
        ['patterns', 'hard', 'creational', 'Prototype pattern in PHP — what is it for?', 'Create objects by cloning an existing configured instance instead of building from scratch — useful when construction is expensive or configurable presets exist. PHP\'s __clone() lets you control deep vs shallow copy during duplication.', ['What traps does __clone have with nested objects?', 'When would factories beat prototypes?']],
        ['patterns', 'medium', 'coupling', 'Give a concrete case where inheritance hurts and composition wins.', 'A Notifier that needs email AND SMS AND log behaviour: inheritance forces choices (EmailNotifier? MultiNotifier subclass?) and multiplies classes. A Notifier composed of a list of Channel objects scales linearly — add a channel, no new subclasses.', ['What about runtime switching between behaviours?', 'How does this affect testing?']],
        ['patterns', 'hard', 'factory', 'When would you deliberately NOT use a factory?', 'When creation is trivial and stable — one constructor call with no branching. A factory that just news up a single class adds indirection with no decision inside; introduce it when a second variant or a config-driven choice actually appears, not speculatively.', ['How do you know a factory has earned its keep?', 'What does YAGNI mean here?']],
        ['patterns', 'medium', 'pattern_principles', 'How do design patterns become premature abstraction?', 'When you reach for a pattern before the second case exists — building a full Abstract Factory for one hardcoded choice. Patterns should name problems you have, not futures you imagine: start with the simplest design and let duplication or change signal which pattern to extract.', ['What signals a pattern is genuinely needed?', 'How does refactoring relate?']],

        // --- Architecture (12) ---
        ['architecture', 'hard', 'enterprise', 'Transaction script vs domain model — when does each fit?', 'Transaction script keeps logic in procedural services over flat data — simple for CRUD-heavy apps with few rules. A domain model moves rules into objects (Invoice, Order) when behaviour grows rich and invariants multiply — the book\'s pivot point between a script and a real model.', ['What are signs you should migrate?', 'Where do DTOs fit in each?']],
        ['architecture', 'medium', 'data_mapper', 'Data mapper vs active record — what is the trade-off?', 'Active record puts persistence methods on the model itself (User::find/save) — fast to build, couples domain to SQL. Data mapper keeps domain objects pure and moves SQL to a mapper — testable, swappable storage, more classes. Choose active record for simple apps, mapper when the domain matters.', ['Which does Laravel Eloquent follow?', 'How does the mapper help unit tests?']],
        ['architecture', 'medium', 'identity_map', 'What problem does the Identity Map solve?', 'It keeps one object per row per request, so repeated finds return the SAME instance instead of competing copies — object identity and in-memory state stay consistent, and you save queries. Without it, two loads of one user diverge and writes overwrite each other.', ['Where does Eloquent\'s identity map live (the relation cache)?', 'When can stale identity map data hurt?']],
        ['architecture', 'medium', 'unit_of_work', 'What is a Unit of Work?', 'It tracks inserts, updates and deletes across many objects and commits them in one batch (one transaction) at flush time — so related changes stay atomic and queries get coalesced. It complements the data mapper: the mapper saves, the unit of work decides when and together.', ['How does this map to Laravel\'s DB transactions?', 'What is dirty tracking?']],
        ['architecture', 'medium', 'request_response', 'What is the front controller pattern?', 'Every HTTP request enters one script (public/index.php) which routes, dispatches and returns the response — no one file per URL. It centralises bootstrapping, auth, error handling and config in one place, which is exactly how Laravel and every modern framework are shaped.', ['What does it mean for static file serving?', 'How do page controllers differ?']],
        ['architecture', 'hard', 'enterprise', 'Page controller vs application controller?', 'A page controller is one class/file per page handling that page only — simple, duplicative. An application controller (front controller style) centralises dispatch: one entry decides which controller/action runs — shared concerns (auth, errors) live in one place instead of being copied per page.', ['Where does routing fit in each?', 'What does the book mean by application controller?']],
        ['architecture', 'medium', 'persistence', 'What is the repository pattern and what does it hide?', 'A repository exposes collection-like access (find, save, all) behind an interface, hiding storage details from the domain. Services depend on the interface, tests use an in-memory fake, and SQL can change without touching business code. It is about a boundary, not about avoiding SQL entirely.', ['Repository vs data mapper — same thing?', 'When does a repository become a leaky abstraction?']],
        ['architecture', 'easy', 'design_principles', 'Why layer an application at all?', 'Layers separate rates of change: UI churns differently from business rules, which churn differently from storage. Each layer speaks only to its neighbour, so you can test business logic without HTTP/SQL and swap one layer (e.g. MySQL to API) without rewriting the rest.', ['What does clean architecture add?', 'What is the cost of too many layers?']],
        ['architecture', 'medium', 'input_validation', 'Where should validation live in an application?', 'At every boundary, defensively: form/request validation before anything runs, domain invariants inside objects so they cannot be constructed invalidly, and DB constraints as the last line. One validation layer is not enough — the boundary check gives friendly errors, the domain and schema guarantee truth.', ['How does Laravel form request validation fit?', 'What are domain invariants?']],
        ['architecture', 'medium', 'api', 'How do you design a REST resource and its status codes?', 'Nouns as paths (/orders/{id}), verbs via HTTP method (GET read, POST create, PATCH partial update, DELETE remove), and honest codes: 200/201 success, 400 bad input, 401/403 auth, 404 missing, 422 validation, 500 faults. Idempotent methods (GET, PUT, DELETE) must be safe to retry.', ['Why does idempotency matter for retries?', 'How do you signal partial success?']],
        ['architecture', 'medium', 'static', 'The book warns about the Registry pattern — why, and what is the modern alternative?', 'A registry is a global bag of services — convenient, but it recreates ambient globals: hidden dependencies, polluted test state, and any code can grab anything. The modern alternative is constructor injection from a container, where dependencies are declared, scoped and swappable.', ['How do facades relate to this warning?', 'When is a genuine singleton configuration object fine?']],
        ['architecture', 'hard', 'enterprise', 'What is an anemic domain model and why is it criticised?', 'Objects that are only data bags with getters/setters while all rules live in services — the domain model exists in name only. Critics say you paid the OO cost (classes everywhere) without the benefit (invariants near state); the fix is moving guarded behaviour back onto the objects.', ['When is a data-only model actually fine?', 'How do you refactor rules out of a service?']],

        // --- Testing (9) ---
        ['testing', 'easy', 'tdd', 'Describe the TDD cycle and why people use it.', 'Red: write a failing test that names the behaviour. Green: make it pass with the smallest change. Refactor: clean the code with tests as a safety net. It forces precise design decisions, gives documentation that never lies, and catches regressions instantly.', ['What do you do when a test is hard to write?', 'Is 100% coverage the goal?']],
        ['testing', 'easy', 'phpunit', 'Unit test vs integration test — when do you write each?', 'Unit tests target one class with collaborators faked — fast, pinpoint failures in logic. Integration tests exercise real pieces together (DB, framework) — slower but prove the wiring. Most suites need both: many units, a thinner integration layer at boundaries.', ['Where does an HTTP test sit?', 'How does Pest relate to PHPUnit?']],
        ['testing', 'medium', 'mocks', 'Mocks vs stubs — what is the difference?', 'A stub is inert: it returns canned answers so the system under test can run (a fake clock returning noon). A mock carries expectations and verifies interactions (assert send() was called once with X). Prefer stubs + asserting outcomes; reach for mocks only when the interaction itself is the contract.', ['What is over-mocking?', 'When is verifying calls genuinely required?']],
        ['testing', 'easy', 'assertions', 'What makes a good assertion?', 'One behaviour per test, asserted specifically: assertSame(42, total()) not assertTrue(!empty($result)). State the expected value literally, so a failure tells you WHAT broke, not merely that something did. Assert the boundary and the invariant, not the implementation details.', ['Why prefer assertSame over assertEquals?', 'What assertion do you avoid?']],
        ['testing', 'easy', 'assertions', 'What is Arrange-Act-Assert?', 'Structure every test in three parts: set up inputs (arrange), exercise the one thing under test (act), verify the outcome (assert). It keeps tests readable, single-purpose, and stops setup from leaking into the assertions.', ['How does Given/When/Then map to it?', 'What should never appear in arrange?']],
        ['testing', 'hard', 'mocks', 'What is over-mocking and why is it dangerous?', 'Mocking everything, including internals of the system under test, asserts on HOW it works rather than WHAT it produces — tests then lock in structure, break on every refactor, and pass while real bugs hide in un-mocked reality. Prefer real objects where they are fast and deterministic.', ['How do you recover a brittle suite?', 'What does the testing pyramid suggest?']],
        ['testing', 'medium', 'tdd', 'Should you test private methods directly?', 'No — test them through the public behaviour they serve. Directly testing privates couples tests to structure so refactoring breaks them; if a private method is complex enough to warrant its own test, its behaviour should probably be a public collaborator.', ['When might protected methods be tested?', 'How does this affect test coverage metrics?']],
        ['testing', 'medium', 'phpunit', 'Coverage is green — why might production still be buggy?', 'Coverage only says which lines ran, not which outcomes were checked. A test that calls everything and asserts nothing (or only happy paths) inflates the number. Quality comes from assertions over edge cases: empty input, boundaries, failures — not from the percentage.', ['What kinds of tests does coverage miss entirely?', 'How do mutation testing relate?']],
        ['testing', 'medium', 'tdd', 'What makes a test suite trustworthy?', 'Deterministic (no randomness, no real network), fast enough to run always, isolated (tests do not depend on order or shared state), and expressive — a failure names the broken behaviour. If developers rerun to see if it is flake, the suite has already stopped protecting you.', ['How do you tame shared state between tests?', 'What role do factories play?']],

        // --- Database (8) ---
        ['database', 'easy', 'pdo', 'Why do prepared statements matter?', 'They separate SQL structure from data: the query is parsed once, values arrive bound as parameters and are never interpreted as SQL. That eliminates classic injection and usually improves repeated execution. Bind values — never concatenate them into the statement.', ['What do emulated prepares change?', 'Can identifiers be bound?']],
        ['database', 'easy', 'transactions', 'What is a transaction and when do you need one?', 'A transaction groups statements so they commit together or roll back together — protecting you when several writes must be consistent (transfer: debit + credit). Without it, a crash between statements leaves the data half-updated.', ['What does ACID mean in one sentence?', 'What does rollBack actually undo?']],
        ['database', 'medium', 'data_mapper', 'Why hydrate rows into objects instead of passing arrays around?', 'Objects carry behaviour and invariants (invoice->approve() enforces rules), so logic lives with state instead of floating in helpers over arrays. Mappers also isolate SQL: the rest of the app sees types, not column names — and tests can fake persistence.', ['Where do DTOs fit if you do not need behaviour?', 'How does hydration hide schema changes?']],
        ['database', 'medium', 'escaping', 'Defend against SQL injection beyond prepared statements.', 'Bound parameters are the primary defence for values; also use an ORM/query builder for structure, least-privilege DB accounts, escape identifiers explicitly when dynamic (allow-list column names), and keep error details out of production responses.', ['Can table names be parameterised?', 'What other injection surfaces exist (command, LDAP)?']],
        ['database', 'medium', 'pdo', 'Raw SQL vs a query builder or ORM — how do you choose?', 'Raw SQL for complex reports, joins and window functions where clarity wins; builder/ORM for everyday CRUD where injection safety and mapping come free. Many codebases mix: ORM for the domain, purpose-built queries for reads that the ORM fights.', ['How do you test hand-written SQL?', 'Where does the data mapper sit between them?']],
        ['database', 'medium', 'pdo', 'How should a long-running script manage its database connection?', 'Open once (or lazily), reuse the PDO handle — connections are expensive; set ERRMODE_EXCEPTION and sane timeouts up front; wrap work in transactions per unit of work, not one giant transaction; and reconnect deliberately when a wait has dropped the link.', ['What breaks with one transaction for the whole import?', 'How do you choose fetch mode?']],
        ['database', 'hard', 'transactions', 'Optimistic vs pessimistic locking — when do you use each?', 'Optimistic: assume no conflict, version-check on write (UPDATE ... WHERE version = ?) and retry if someone else changed the row — great for web requests. Pessimistic: lock rows up front (SELECT ... FOR UPDATE) when conflicts are likely or lost updates are costly — careful, it can block other writers.', ['What happens when the version check fails?', 'How do retries interact with idempotency?']],
        ['database', 'medium', 'pdo', 'What fetch styles does PDO offer and which do you prefer?', 'FETCH_ASSOC for named columns in app code, FETCH_CLASS to hydrate into your own classes directly, FETCH_OBJ for quick scripts, and FETCH_COLUMN for single-value lists. Prefer associative or class hydration over indexed numerics — column order is a fragile dependency.', ['How does FETCH_CLASS relate to mappers?', 'Why avoid numeric indexes?']],
    ];

    public function run(): void
    {
        $conceptIds = Concept::query()->pluck('id', 'slug');
        $ord = 0;

        foreach (self::QUESTIONS as $row) {
            [$topic, $difficulty, $conceptSlug, $question, $answer, $followUps] = $row;
            $ord++;

            InterviewQuestion::updateOrCreate(
                ['question' => $question],
                [
                    'concept_id' => $conceptIds[$conceptSlug] ?? null,
                    'topic' => $topic,
                    'model_answer' => $answer,
                    'follow_ups' => $followUps,
                    'difficulty' => ExerciseDifficulty::from($difficulty),
                    'ord' => $ord,
                    'source' => ProvenanceSource::Ai,
                    'status' => ContentStatus::Published,
                    'ai_model' => 'gpt-4o',
                    'ai_generated_at' => now(),
                    'ai_prompt_version' => 'phase9-seed',
                ],
            );
        }
    }
}
