<?php

namespace App\Livewire\Admin;

use App\Enums\AiActor;
use App\Enums\ContentStatus;
use App\Jobs\GenerateLessonJob;
use App\Models\Concept;
use App\Models\ContentVersion;
use App\Models\Diagram;
use App\Models\Exercise;
use App\Models\Flashcard;
use App\Models\Lesson;
use App\Models\QuizQuestion;
use App\Models\User;
use App\Services\Content\ContentApprover;
use App\Services\Content\Diff;
use Illuminate\Contracts\View\View;
use Illuminate\Database\Eloquent\Collection;
use Illuminate\Database\Eloquent\Model;
use Livewire\Attributes\Title;
use Livewire\Component;

/**
 * /admin/review - the human gate for Pipeline A: side-by-side diff of the
 * current AI draft vs the last approved version, Approve / Reject /
 * Regenerate (docs/08 screen table, docs/15 Phase 7).
 */
#[Title('Review Queue')]
class ReviewQueue extends Component
{
    public ?string $selectedType = null;

    public ?int $selectedId = null;

    public ?string $notice = null;

    /** @var list<array{op: string, line: string}> */
    public array $diff = [];

    public ?string $diffSummary = null;

    public function select(string $type, int $id): void
    {
        $approver = app(ContentApprover::class);
        $entity = $this->find($type, $id);

        if ($entity === null) {
            $this->notice = "Entity {$type} #{$id} not found.";

            return;
        }

        $payload = $approver->snapshot($type, $entity);

        $previous = ContentVersion::query()
            ->where('entity_type', $type)
            ->where('entity_id', $id)
            ->latest('id')
            ->first();

        $diff = app(Diff::class);

        $this->diff = $diff->lines($previous?->payload['lines'] ?? [], $payload['lines'] ?? []);
        $this->diffSummary = $diff->summary($previous?->payload['lines'] ?? null, $payload['lines'] ?? []);
        $this->selectedType = $type;
        $this->selectedId = $id;
        $this->notice = null;
    }

    public function approve(ContentApprover $approver): void
    {
        if ($this->selectedType === null || $this->selectedId === null || ! $this->authorized()) {
            return;
        }

        $user = auth()->user();

        if (! $user instanceof User) {
            return;
        }

        $entity = $approver->approve($this->selectedType, $this->selectedId, $user);

        $this->notice = ucfirst(str_replace('_', ' ', $this->selectedType))." #{$entity->getKey()} published.";
        $this->clear();
    }

    public function reject(ContentApprover $approver): void
    {
        if ($this->selectedType === null || $this->selectedId === null || ! $this->authorized()) {
            return;
        }

        $entity = $approver->reject($this->selectedType, $this->selectedId);

        $this->notice = ucfirst(str_replace('_', ' ', $this->selectedType))." #{$entity->getKey()} moved back to draft.";
        $this->clear();
    }

    public function regenerate(int $lessonId): void
    {
        if (! $this->authorized()) {
            return;
        }

        $lesson = Lesson::query()->find($lessonId);

        if ($lesson === null || $lesson->section_id === null) {
            $this->notice = 'This lesson has no book section to regenerate from.';

            return;
        }

        $payload = app(ContentApprover::class)->snapshot('lesson', $lesson);

        ContentVersion::query()->create([
            'entity_type' => 'lesson',
            'entity_id' => $lesson->id,
            'payload' => $payload,
            'actor' => AiActor::Ai,
            'diff_summary' => 'regenerated by admin',
        ]);

        GenerateLessonJob::dispatch($lesson->section_id, $lesson->stage_id, force: true);

        $this->notice = "Regeneration queued for lesson #{$lesson->id} - watch /admin/import-jobs.";
    }

    public function clear(): void
    {
        $this->selectedType = null;
        $this->selectedId = null;
        $this->diff = [];
        $this->diffSummary = null;
    }

    /**
     * Route middleware enforces admin access; repeat it here because
     * Livewire actions can be invoked outside the original route context.
     */
    private function authorized(): bool
    {
        $user = auth()->user();

        return $user instanceof User && $user->isAdmin();
    }

    public function render(): View
    {
        $inReview = [ContentStatus::InReview->value];

        return view('livewire.admin.review-queue', [
            'lessons' => Lesson::query()->whereIn('status', $inReview)->orderByDesc('id')->get(),
            'others' => collect()
                ->merge($this->rows('concept', Concept::query()->whereIn('status', $inReview)->orderByDesc('id')->limit(30)->get()))
                ->merge($this->rows('exercise', Exercise::query()->whereIn('status', $inReview)->orderByDesc('id')->limit(30)->get()))
                ->merge($this->rows('quiz_question', QuizQuestion::query()->whereIn('status', $inReview)->orderByDesc('id')->limit(30)->get()))
                ->merge($this->rows('flashcard', Flashcard::query()->whereIn('status', $inReview)->orderByDesc('id')->limit(30)->get()))
                ->merge($this->rows('diagram', Diagram::query()->whereIn('status', $inReview)->orderByDesc('id')->limit(30)->get()))
                ->values(),
        ]);
    }

    /**
     * @template TEntity of Model
     *
     * @param  Collection<int, TEntity>  $entities
     * @return list<array{type: string, id: int, label: string}>
     */
    private function rows(string $type, $entities): array
    {
        $rows = [];

        foreach ($entities as $entity) {
            $label = (string) ($entity->name ?? $entity->title ?? $entity->prompt ?? $entity->front ?? $entity->stem ?? $entity->explanation ?? $entity->mermaid_source ?? '');
            $rows[] = ['type' => $type, 'id' => (int) $entity->getKey(), 'label' => mb_substr($label, 0, 70)];
        }

        return $rows;
    }

    private function find(string $type, int $id): ?Model
    {
        $class = ContentApprover::ENTITIES[$type] ?? null;

        return $class !== null ? $class::query()->find($id) : null;
    }
}
