<?php

namespace App\Enums;

/**
 * Origin of graph content (`concepts.source`, `concept_prerequisites.source`):
 * extracted from the book, generated by AI, or curated by hand in project
 * docs (05-knowledge-map.md). Distinct from ProvenanceSource (book/ai/hybrid)
 * which tags full lesson blocks.
 */
enum ContentSource: string
{
    case Book = 'book';
    case Ai = 'ai';
    case Manual = 'manual';

    public function label(): string
    {
        return match ($this) {
            self::Book => 'Book',
            self::Ai => 'AI-generated',
            self::Manual => 'Curated',
        };
    }
}
